param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\software install\IAR430\common\bin\cspybat" -f "E:\徐颖俊工作资料\新加坡资料\刘梦晨资料\刘梦晨程序\msp430\msp430\Projects\settings\4xADS1220_FR4133_PT100_PT1K_V2_EW62.Debug.general.xcl" --backend -f "E:\徐颖俊工作资料\新加坡资料\刘梦晨资料\刘梦晨程序\msp430\msp430\Projects\settings\4xADS1220_FR4133_PT100_PT1K_V2_EW62.Debug.driver.xcl" 
}
else
{
& "D:\software install\IAR430\common\bin\cspybat" -f "E:\徐颖俊工作资料\新加坡资料\刘梦晨资料\刘梦晨程序\msp430\msp430\Projects\settings\4xADS1220_FR4133_PT100_PT1K_V2_EW62.Debug.general.xcl" --debug_file=$debugfile --backend -f "E:\徐颖俊工作资料\新加坡资料\刘梦晨资料\刘梦晨程序\msp430\msp430\Projects\settings\4xADS1220_FR4133_PT100_PT1K_V2_EW62.Debug.driver.xcl" 
}
