#ifndef __BSP_HARDWARE_CONFIG_H
#define __BSP_HARDWARE_CONFIG_H

#include "io.h"

#define LED1_PIN				GPIO_Pin_3
#define LED1_PORT				GPIOB
#define LED1_CLK				RCC_APB2Periph_GPIOB
#define LED1_PIN_SRC			GPIO_PinSource3

#define LED2_PIN				GPIO_Pin_0
#define LED2_PORT				GPIOA
#define LED2_CLK				RCC_APB2Periph_GPIOA
#define LED2_PIN_SRC			GPIO_PinSource0

#define CLI_DB_USART_TYPE		UART4
#define CLI_DB_USART_CLK		RCC_APB1Periph_UART4
#define CLI_DB_USART_BAUDRATE 	115200
#define CLI_DB_USART_WORDLEN 	USART_WordLength_8b
#define CLI_DB_USART_STOPBITS	USART_StopBits_1
#define CLI_DB_USART_PARITY		USART_Parity_No
#define CLI_DB_USART_MODE		(USART_Mode_Rx|USART_Mode_Tx)
#define CLI_DB_USART_HARDFLOW	USART_HardwareFlowControl_None
#define CLI_DB_USART_IOREMAP	0

#define CLI_DB_USART_PORT_RX_PIN		GPIO_Pin_1
#define CLI_DB_USART_PORT_RX_PORT		GPIOA
#define CLI_DB_USART_PORT_RX_CLK   		RCC_APB2Periph_GPIOA 
#define CLI_DB_USART_PORT_RX_PIN_SRC	GPIO_PinSource1

#define CLI_DB_USART_PORT_TX_PIN		GPIO_Pin_0
#define CLI_DB_USART_PORT_TX_PORT		GPIOA
#define CLI_DB_USART_PORT_TX_CLK   		RCC_APB2Periph_GPIOA
#define CLI_DB_USART_PORT_TX_PIN_SRC	GPIO_PinSource0

#define CLI_DB_USART_IRQ_ENABLE			ENABLE
#define CLI_DB_USART_IRQ_TYPE			USART_IT_RXNE
#define CLI_DB_USART_NVIC_IRQ_CHAN		UART4_IRQn
#define CLI_DB_USART_NVIC_IRQ_PRE_PRI	0xF
#define CLI_DB_USART_NVIC_IRQ_SUB_PRI	0
#define CLI_DB_USART_NVIC_IRQ_CMD		ENABLE

#define WIFI_USART_TYPE				USART2
#define WIFI_USART_CLK				RCC_APB1Periph_USART2 
#define WIFI_USART_BAUDRATE 		115200
#define WIFI_USART_WORDLEN 			USART_WordLength_8b
#define WIFI_USART_STOPBITS			USART_StopBits_1
#define WIFI_USART_PARITY			USART_Parity_No
#define WIFI_USART_MODE				(USART_Mode_Rx|USART_Mode_Tx)
#define WIFI_USART_HARDFLOW			USART_HardwareFlowControl_None
#define WIFI_USART_IOREMAP			0

#define WIFI_USART_PORT_RX_PIN		GPIO_Pin_3
#define WIFI_USART_PORT_RX_PORT		GPIOA
#define WIFI_USART_PORT_RX_CLK   	RCC_APB2Periph_GPIOA
#define WIFI_USART_PORT_RX_PIN_SRC	GPIO_PinSource3

#define WIFI_USART_PORT_TX_PIN		GPIO_Pin_2
#define WIFI_USART_PORT_TX_PORT		GPIOA
#define WIFI_USART_PORT_TX_CLK   	RCC_APB2Periph_GPIOA
#define WIFI_USART_PORT_TX_PIN_SRC	GPIO_PinSource2

#define WIFI_USART_IRQ_ENABLE		ENABLE
#define WIFI_USART_IRQ_TYPE			USART_IT_RXNE
#define WIFI_USART_NVIC_IRQ_CHAN	USART2_IRQn
#define WIFI_USART_NVIC_IRQ_PRE_PRI	0x9
#define WIFI_USART_NVIC_IRQ_SUB_PRI	0
#define WIFI_USART_NVIC_IRQ_CMD		ENABLE

#define RS485_USART_TYPE				USART1
#define RS485_USART_CLK				RCC_APB2Periph_USART1 
#define RS485_USART_BAUDRATE 		9600
#define RS485_USART_WORDLEN 			USART_WordLength_8b
#define RS485_USART_STOPBITS			USART_StopBits_1
#define RS485_USART_PARITY			USART_Parity_No
#define RS485_USART_MODE				(USART_Mode_Rx | USART_Mode_Tx)
#define RS485_USART_HARDFLOW			USART_HardwareFlowControl_None
#define RS485_USART_IOREMAP			0

#define RS485_USART_PORT_RX_PIN		GPIO_Pin_10
#define RS485_USART_PORT_RX_PORT		GPIOA
#define RS485_USART_PORT_RX_CLK   	RCC_APB2Periph_GPIOA
#define RS485_USART_PORT_RX_PIN_SRC	GPIO_PinSource10

#define RS485_USART_PORT_TX_PIN		GPIO_Pin_9
#define RS485_USART_PORT_TX_PORT		GPIOA
#define RS485_USART_PORT_TX_CLK   	RCC_APB2Periph_GPIOA
#define RS485_USART_PORT_TX_PIN_SRC	GPIO_PinSource9

#define RS485_USART_PORT_DE_PIN		GPIO_Pin_14
#define RS485_USART_PORT_DE_PORT		GPIOB
#define RS485_USART_PORT_DE_CLK   	RCC_APB2Periph_GPIOB
#define RS485_USART_PORT_DE_PIN_SRC	GPIO_PinSource14

#define RS485_USART_IRQ_ENABLE		ENABLE
#define RS485_USART_IRQ_TYPE			USART_IT_RXNE
#define RS485_USART_NVIC_IRQ_CHAN	USART1_IRQn
#define RS485_USART_NVIC_IRQ_PRE_PRI	0x9
#define RS485_USART_NVIC_IRQ_SUB_PRI	0
#define RS485_USART_NVIC_IRQ_CMD		ENABLE

#endif
/*--------------------------end of file----------------------*/

